# Práctico 4:

1. Implementar un pipeline de clasificación con la muestra que se vió en clase. El código para traer el dataset es el siguiente:

In [9]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version=1, as_frame=False)
print(mnist.keys())
X, y = mnist["data"], mnist["target"]

/home/fran/Documentos/5 AÑO/Sistemas Inteligentes carpeta/Sistemas-Inteligentes/Clase 4/my_env/lib/python3.8/site-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url'])


In [11]:
import numpy as np
# Casteamos a int
y = np.array([int(n) for n in y])

print(y)

[5 0 4 ... 4 5 6]


In [12]:
# Escalamos todos los datos a 0 1 (Normalización)
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X = scaler.fit_transform(X)

In [13]:
# Vamos a modelar la detección para el numero 5

from sklearn.model_selection import train_test_split

#Primero vamos a crear los dataset de evaluación y entrenamiento
X_train_set, X_test_set = train_test_split(X, test_size=0.2, random_state=42)

y_train_set, y_test_set = train_test_split(y, test_size=0.2, random_state=42)

print(X_train_set)

print(X_test_set)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [14]:
# Filtramos las etiquetas solo para los valores 5
y_train_set_5 = (y_train_set == 5)

y_test_set_5 = (y_test_set == 5)

print(list(filter(lambda X: X is True, y_test_set_5.tolist())))

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, Tru

In [ ]:
# Importamos el clasificado binario
from sklearn.linear_model import SGDClassifier

sgd_clf = SGDClassifier(random_state=42)

sgd_clf.fit(X_train_set, y_train_set_5)

SGDClassifier(random_state=42)

In [ ]:
# Probamos el modelo
sgd_clf.predict([X[11]])

array([ True])

In [ ]:
# Midiendo precisión usando validación cruzada
from sklearn.model_selection import cross_val_score

cross_val_score(sgd_clf, X_train_set, y_train_set_5, cv=3, scoring = "accuracy")

array([0.97192907, 0.96855413, 0.96024858])

In [ ]:
# Medimos la precisión usando el "dummy classifier"

from sklearn.dummy import DummyClassifier

never_5_clf = DummyClassifier(strategy="most_frequent")

# volvemos a medir la precisión usando validación cruzada

cross_val_score(never_5_clf, X_train_set, y_train_set_5, cv=3, scoring = "accuracy")

array([0.91000161, 0.91000161, 0.90999679])

In [61]:
# Matriz de confusión
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix

y_train_pred = cross_val_predict(sgd_clf, X_train_set, y_train_set_5, cv=3)

confusion_matrix(y_train_set_5, y_train_pred)

# Los arroja en el siguiente orden: Verdadero negativo, verdadero positivo, Falso negativo, Falso positivo

NameError: name 'y_train_set_5' is not defined

In [ ]:
# Implementación de precisión (V.P / V.P + F.P)
from sklearn.metrics import precision_score, recall_score

precision = precision_score(y_train_set_5, y_train_pred)

recall = recall_score(y_train_set_5, y_train_pred)

print("Precision: {}".format(precision))

print("Recall: {}".format(recall))

Precision 0.8515332009706597
Recall 0.7658730158730159


In [ ]:
# Medición del F1 score

from sklearn.metrics import f1_score

f1 = f1_score(y_train_set_5, y_train_pred)

print(f1)

0.8064347644416588


2. Luego conteste las siguientes preguntas:
- ¿Que es un clasificador Binario?
- ¿Por qué un modelo con gran accuracy puede que no ser un buen modelo?
- ¿Por qué existe un trade off entre presicion y recall?
- ¿F1 es la mejor métrica que se puede utilizar al momento de optimizar un modelo? Justifique.
- ¿Para que sirve la curva ROC?
3. Utilice el clasificador KNeighborsClassifier y optimice los hiperparámetros utilizando GridSearch. ¿Qué accuracy se alcanza en el test set?