# Ejercicios de la librería Numpy

0. Importa la librería numpy como np

In [ ]:
import numpy as np

1. Crear un arreglo de 10 ceros

In [3]:
import numpy as np

print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2. Crear un arreglo de 10 unos

In [4]:
import numpy as np

print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


3. Crear un arreglo de 10 cincos

In [5]:
import numpy as np

print(np.full(10,5))

[5 5 5 5 5 5 5 5 5 5]


4. Crear un arreglo con todos los numeros pares del 10 al 50

In [7]:
import numpy as np

print(np.arange(10,50,2))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


5. Crear una matriz 3x3 con valores del 0 al 8

In [10]:
import numpy as np

m = np.array([[0,1,2],[3,4,5],[6,7,8]])

print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


6. Crear una matriz de identidad de 3x3

In [11]:
import numpy as np

print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


7. Utilizar numpy para geneara un numero aleatorio entre 0 y 1

In [23]:
import numpy as np


print(np.random.random(1))

[0.49846318]


8. Utilizar numpy para generar un arreglo de 25 numeros aleatorioas con una distribucion normal

In [27]:
import numpy as np

print(np.random.normal(0,1,25))

[-0.7764684  -0.85224151  0.61728901  1.80756637  1.26374407  0.14008713
  0.39682123  1.17678026  1.52784737  0.16317999 -1.22881327  0.0033783
 -1.60394622  0.91013116 -0.58159204  0.12716746 -0.02210578 -0.44139044
  0.9679164   0.00828552 -0.20799608 -0.85885108  0.82409207  0.27162648
  0.65779984]


9. Crear la siguiente matriz

In [ ]:
#no hacer

10. Crear un arreglo de 20 valores lineales entre 0 y 1

In [29]:
import numpy as np

print(np.linspace(0,1,20))

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


### Seleccion e indices de Numpy
11. Se te daran varias matrices, se te pide replicar el resultado

In [2]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [48]:
import numpy as np

mat1 = np.arange(12,16)
mat2 = np.arange(17,21)
mat3 = np.arange(22,26)

mats = (np.concatenate([mat1,mat2,mat3]))

mats.reshape(3,4)

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [53]:
import numpy as np

a = np.array([[15,16,17], [18,19,20]])
print(a[1, 2])

20


In [58]:
import numpy as np

a = np.arange(2,13,5)


a.reshape(3,1)


array([[ 2],
       [ 7],
       [12]])

In [59]:
import numpy as np

a = np.arange(21,26)

a.reshape(1,5)

array([[21, 22, 23, 24, 25]])

In [61]:
import numpy as np

a = np.arange(16,26)

a.reshape(2,5)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Luego continua con:
- Obten la suma de los valores de `mat`
- Obten la desviacion estandar de los valores de `mat`
- Obten la suma de las columnas de los valores de `mat`

In [66]:
import numpy as np

mat = np.arange(1,26).reshape(5,5)
mat

print(mat.sum())
print(mat.std())
print(mat.sum(0)) #axis 0 suma columnas, axis 1 suma filas

325
7.211102550927978
[55 60 65 70 75]


# Ejercicios de la Librería Pandas

1. Escribir un programa que pregunte al usuario por las ventas de un rango de años y muestre por pantalla una serie con los datos de las ventas indexada por los años, antes y después de aplicarles un descuento del 10%.

In [28]:
import pandas as pd

def calcular_ventas():
    v = pd.Series(index=range(1,6))
    for i in v.index:
        v[i] = float(input("Ingrese ventas para el anio "+str(i)))
    return v

def aplicar_descuento(v):
    return v*0.9

v = calcular_ventas()
v_descuento = aplicar_descuento(v)
print("Ventas")
print(v)
print("Ventas con descuento")   #para mostrar los resultados en una tablita uso DataFrame
print(v_descuento)





/tmp/ipykernel_5299/1893468687.py:4: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  v = pd.Series(index=range(1,6))


Ventas
1     5.0
2     8.0
3    77.0
4     5.0
5     8.0
dtype: float64
Ventas con descuento
1     4.5
2     7.2
3    69.3
4     4.5
5     7.2
dtype: float64


2. Escribir una función que reciba un diccionario con las notas de los alumno de un curso y devuelva una serie con la nota mínima, la máxima, media y la desviación típica.

In [68]:
import pandas as pd
s = pd.Series({'Francisco':9.50, 'Pedro':3.80, 'Martin':7.85, 'Jose':8.70})

def calculo_notas():
    #print(s)
   
    nota_min = round(s.min(), 2)
    nota_max =  round(s.max(),2)    #para redonear el maximo tuve que redonear todas las funciones(min,media,std)
    media = round(s.mean(),2)
    desv = round(s.std(),2)
    serie = pd.Series({'Nota Minima': nota_min,'Nota Maxima': nota_max,'Media': media, 'Desviacion tipica': desv})
    return serie

calculo_notas()

Nota Minima          3.80
Nota Maxima          9.50
Media                7.46
Desviacion tipica    2.53
dtype: float64

3. Escribir una función que reciba un diccionario con las notas de los alumnos de un curso y devuelva una serie con las notas de los alumnos aprobados ordenadas de mayor a menor.

In [75]:
import pandas as pd
s = pd.Series({'Francisco':9.50, 'Pedro':3.80, 'Martin':7.85, 'Jose':8.70})

def aprobados():
    ap = (s[s>6])
    print(ap.sort_values(ascending = False))

aprobados()

Francisco    9.50
Jose         8.70
Martin       7.85
dtype: float64


4. Escribir programa que genere y muestre por pantalla un DataFrame con los datos de la tabla siguiente:

| Mes | Ventas | Gastos |
| --- | --- | --- |
| Enero | 30500 | 22000 |
| Febrero | 35600 | 23400 |
| Marzo | 28300 | 18100 |
| Abril | 33900 | 20700 |

In [1]:
import pandas as pd
datos = {'Mes':['Enero', 'Febrero', 'Marzo', 'Abril'],
         'Ventas':[30500,35600,28300,33900],
         'Gastos':[22000,23400,18100,20700]
        }
df = pd.DataFrame(datos)
print(df)

       Mes  Ventas  Gastos
0    Enero   30500   22000
1  Febrero   35600   23400
2    Marzo   28300   18100
3    Abril   33900   20700


5. Escribir una función que reciba un DataFrame con el formato del ejercicio anterior, una lista de meses, y devuelva el balance (ventas - gastos) total en los meses indicados.

In [28]:
import pandas as pd

datos = {'Mes':['Enero', 'Febrero', 'Marzo', 'Abril'],
         'Ventas':[30500,35600,28300,33900],
         'Gastos':[22000,23400,18100,20700]
        }

df = pd.DataFrame(datos)

def balance_total(df,meses):
    df['Balance'] = df.Ventas - df.Gastos
    return df.set_index('Mes').loc[meses,'Balance'] #para obtener un total pongo .sum()
   
balance_total(df, ['Enero','Febrero','Marzo'])

Mes
Enero       8500
Febrero    12200
Marzo      10200
Name: Balance, dtype: int64


6. El fichero cotizacion.csv contiene las cotizaciones de las empresas del IBEX35 con las siguientes columnas: nombre (nombre de la empresa), Final (precio de la acción al cierre de bolsa), Máximo (precio máximo de la acción durante la jornada), Mínimo (precio mínimo de la acción durante la jornada), volumen (Volumen al cierre de bolsa), Efectivo (capitalización al cierre en miles de euros). Construir una función que construya un DataFrame a partir del un fichero con el formato anterior y devuelva otro DataFrame con el mínimo, el máximo y la media de dada columna.

In [50]:
import pandas as pd

def csv_cotizacion():
    df = pd.read_csv('csv/cotizacion.csv',sep=';', decimal=',', thousands='.', index_col=0) #asi no aparece la columna Nombre
    min = df.min()
    max = df.max()
    media = df.mean()
    return pd.DataFrame([min,max,media],index=['Minimo', 'Maximo', 'Media'])

display(csv_cotizacion())

Final        Máximo        Mínimo       Volumen    Efectivo
Minimo      1.016500      4.067500      1.016500  1.221000e+03    2343.090
Maximo  19705.000000  19875.000000  19675.000000  3.612969e+07  145765.440
Media    2796.768757   3170.113357   3136.510471  4.252279e+06   31767.778

7. El fichero titanic.csv contiene información sobre los pasajeros del Titanic. Escribir un programa con los siguientes requisitos:

    1. Generar un DataFrame con los datos del fichero.
    2. Mostrar por pantalla las dimensiones del DataFrame, el número de datos que contiene, los nombres de sus columnas y filas, los tipos de datos de las columnas, las 10 primeras filas y las 10 últimas filas
    3. Mostrar por pantalla los datos del pasajero con identificador 148.
    4. Mostrar por pantalla las filas pares del DataFrame.
    5. Mostrar por pantalla los nombres de las personas que iban en primera clase ordenadas alfabéticamente.
    6. Mostrar por pantalla el porcentaje de personas que sobrevivieron y murieron.
    7. Mostrar por pantalla el porcentaje de personas que sobrevivieron en cada clase.
    8. Eliminar del DataFrame los pasajeros con edad desconocida.
    9. Mostrar por pantalla la edad media de las mujeres que viajaban en cada clase.
    10. Añadir una nueva columna booleana para ver si el pasajero era menor de edad o no.
    11. Mostrar por pantalla el porcentaje de menores y mayores de edad que sobrevivieron en cada clase.

In [10]:
import pandas as pd
#1 - Generar un DataFrame con los datos del fichero.
df = pd.read_csv("csv/titanic.csv",sep=',')
#display(df)

#2 - Mostrar por pantalla las dimensiones del DataFrame, el número de datos que contiene, los nombres de sus columnas y filas, los tipos de datos de las columnas, las 10 primeras filas y las 10 últimas filas
#print("Dimensiones: ", df.shape)
#print("Numero de datos: ",df.size)
#print("Nombre de columnas: ", df.columns)
#print("Nombre de filas: ", df.index)
#print("Tipo de datos de las columnas: ", df.dtypes)
#print("Nombre de filas: ", df.index)
#print("10 primeras filas: ", df.head(10))
#print("10 ultimas filas: ", df.tail(10))

#3 - Mostrar por pantalla los datos del pasajero con identificador 148.
#print(df.loc[148-1])


#4
#print(df.iloc[::2]) #esto :: es muy util para ir de 2 en 2, de 3 en 3. Del lado izquierdo se pone desde que fila se comienza y del lado derecho de los dos puntos se pone de cuanto en cunato se quiere ir

#5
#print(df[df["Pclass"]==1]["Name"].sort_values())

#6
#num_filas = df.shape[0]
#print("Porcentaje de sobrevivientes: ",df[df["Survived"]==1]["Survived"].count()*100/num_filas)
#print("Porcentaje de muertes: ",df[df["Survived"]==0]["Survived"].count()*100/num_filas)

#7
num_1clase = df[(df["Survived"]==1) & (df["Pclass"]==1)] ["Survived"].shape[0] # = 136
porcentaje1 = num_1clase*100/(df[(df["Pclass"]==1)].shape[0]) #(df[(df["Pclass"]==1)].shape[0]) = 216

num_2clase = df[(df["Survived"]==1) & (df["Pclass"]==2)] ["Survived"].shape[0] # = 87
porcentaje2 = num_2clase*100/(df[(df["Pclass"]==2)].shape[0]) 

num_3clase = df[(df["Survived"]==1) & (df["Pclass"]==3)] ["Survived"].shape[0] # = 119
porcentaje3 = num_3clase*100/(df[(df["Pclass"]==3)].shape[0]) 

print("Porcentaje de sobrevivientes en 1era clase: "+ str(porcentaje1)) #tambien puedo usar shape[0] para contar el nro de filas
print("Porcentaje de sobrevivientes en 2da clase: "+ str(porcentaje2))
print("Porcentaje de sobrevivientes en 3era clase: "+ str(porcentaje3))

119
Porcentaje de sobrevivientes en 1era clase: 62.96296296296296
Porcentaje de sobrevivientes en 2da clase: 47.28260869565217


NameError: name 'porcentaje3' is not defined

8. Los ficheros emisiones-2016.csv, emisiones-2017.csv, emisiones-2018.csv y emisiones-2019.csv, contienen datos sobre las emisiones contaminates en la ciudad de Madrid en los años 2016, 2017, 2018 y 2019 respectivamente. Escribir un programa con los siguientes requisitos:

    1. Generar un DataFrame con los datos de los cuatro ficheros.
    2. Filtrar las columnas del DataFrame para quedarse con las columnas ESTACION, MAGNITUD, AÑO, MES y las correspondientes a los días D01, D02, etc.
    3. Reestructurar el DataFrame para que los valores de los contaminantes de las columnas de los días aparezcan en una única columna.
    4. Añadir una columna con la fecha a partir de la concatenación del año, el mes y el día (usar el módulo datetime).
    5. Eliminar las filas con fechas no válidas (utilizar la función isnat del módulo numpy) y ordenar el DataFrame por estaciones contaminantes y fecha.
    6. Mostrar por pantalla las estaciones y los contaminantes disponibles en el DataFrame.
    7. Crear una función que reciba una estación, un contaminante y un rango de fechas y devuelva una serie con las emisiones del contaminante dado en la estación y rango de fechas dado.
    8. Mostrar un resumen descriptivo (mínimo, máximo, media, etc.) para cada contaminante.
    9. Mostrar un resumen descriptivo para cada contaminante por distritos.
    10. Crear una función que reciba una estación y un contaminante y devuelva un resumen descriptivo de las emisiones del contaminante indicado en la estación indicada.
    11. Crear una función que devuelva las emisiones medias mensuales de un contaminante y un año dados para todos las estaciones.
    12. Crear un función que reciba una estación de medición y devuelva un DataFrame con las medias mensuales de los distintos tipos de contaminantes.

# Ejercicios de la librería Matplotlib

1. Escribir un programa que pregunte al usuario por las ventas de un rango de años y muestre por pantalla un diagrama de líneas con la evolución de las ventas.

2. Escribir una función que reciba una diccionario con las notas de las asignaturas de un curso y una cadena con el nombre de un color y devuelva un diagrama de barras de las notas en el color dado.

3. Escribir una función que reciba una serie de Pandas con las notas de los alumnos de un curso y devuelva un diagrama de cajas con las notas. El diagrama debe tener el título “Distribución de notas”.

4. Escribir una función que reciba una serie de Pandas con el número de ventas de un producto durante los meses de un trimestre y un título y cree un diagrama de sectores con las ventas en formato png con el titulo dado. El diagrama debe guardarse en un fichero con formato png y el título dado.

5. Escribir una función que reciba una serie de Pandas con el número de ventas de un producto por años y una cadena con el tipo de gráfico a generar (lineas, barras, sectores, areas) y devuelva un diagrama del tipo indicado con la evolución de las ventas por años y con el título “Evolución del número de ventas”.

6. Escribir una función que reciba un dataframe de Pandas con los ingresos y gastos de una empresa por meses y devuelva un diagrama de líneas con dos líneas, una para los ingresos y otra para los gastos. El diagrama debe tener una leyenda identificando la línea de los ingresos y la de los gastos, un título con el nombre “Evolución de ingresos y gastos” y el eje y debe empezar en 0.

7. El fichero bancos.csv contiene las cotizaciones de los principales bancos de España con : **Empresa** (nombre de la empresa), **Apertura** (precio de la acción a la apertura de bolsa), **Máximo** (precio máximo de la acción durante la jornada), **Mínimo** (precio mínimo de la acción durante la jornada), **Cierre** (precio de la acción al cierre de bolsa), **Volumen** (volumen al cierre de bolsa). Construir una función reciba el fichero bancos.csv y cree un diagrama de líneas con las series temporales de las cotizaciones de cierre de cada banco.

8. El fichero titanic.csv contiene información sobre los pasajeros del Titanic. Crear un dataframe con Pandas y a partir de él generar los siguientes diagramas.
    1. Diagrama de sectores con los fallecidos y supervivientes.
    2. Histograma con las edades.
    3. Diagrama de barras con el número de personas en cada clase.
    4. Diagrama de barras con el número de personas fallecidas y supervivientes en cada clase.
    5. Diagrama de barras con el número de personas fallecidas y supervivientes acumuladas en cada clase.